version: '3'
services:
  web:
    container_name: web
    networks:
      testnet: {}
    build: .
    ports:
      - "5000:5000"
  redis:
    container_name: redis
    networks:
      testnet: {}    
    image: "redis:alpine"

networks:
  testnet:    