name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: Docker up
        run: docker-compose -f docker-compose.yml -f docker-compose.selenium.yml up -d
      - name: Docker ps
        run: docker ps
      - name: Wait for services start
        run: |
          docker run --network container:web appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
          docker run --network container:selenium appropriate/curl -s --retry 10 --retry-connrefused http://localhost:4444/
          echo "App and Selenium containers are up and running"
      - name: Run UI Tests
        run: |
          pip install wheel
          pip install selenium
          pip install pytest
          pytest
      - name: Docker down
        run: docker-compose -f docker-compose.yml -f docker-compose.selenium.yml down
      - name: Docker ps
        run: docker ps

# Install act
# curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
# act --platform ubuntu-latest=lucasalt/act_base:latest
