name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: Docker up
        run: docker-compose -f docker-compose.yml -f docker-compose.selenium.yml up -d
      - name: Docker ps
        run: docker ps
      - name: Pip install
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel setuptools tox
          pip install wait-for-it
          pip install selenium
          pip install pytest
      - name: Wait for services start
        run: |
          # docker run --network container:web appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
          # docker run --network container:selenium appropriate/curl -s --retry 10 --retry-connrefused http://localhost:4444/
          echo "App and Selenium containers are up and running"
      - name: Run UI Tests
        run: pytest
      - name: Docker down
        run: docker-compose -f docker-compose.yml -f docker-compose.selenium.yml down
      - name: Docker ps
        run: docker ps

# Install act
# curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
# act --platform ubuntu-latest=lucasalt/act_base:latest
